name: Python application tests and coverage

on: [push]

jobs:
  build:
    name: Tests and coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.9"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install codacy-coverage
          pip install -U drf-yasg
      - name: Codacy Coverage Reporter
        run: python-codacy-coverage -t ${{ secrets.CODACY_PROJECT_TOKEN }} -r coverage.xml
